[package]
name = "aisstant"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/daraber/aisstant"
authors = ["daraber"]
description = "Generate CLI commands from natural language"
categories = ["command-line-utilities"]